FROM jupyter/scipy-notebook

LABEL description="This is custom Docker Image data science."

WORKDIR /home/jovyan/

COPY requirements.txt requirements.txt
RUN pip install --upgrade pip 
RUN pip install -r  requirements.txt
WORKDIR /home/jovyan/work

