version: "3"

services: 
  notebook:
    container_name: jupyter
    build: .
    ports: 
    
      - "8888:8888"
    volumes: 
      - ./notebooks:/home/jovyan/work
    # environment:
    #   - JUPYTER_ENABLE_LAB=False
    # command: "start-notebook.sh"
      