version: '3.3'
volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: $PWD/database
      o: bind
services:
  db:
    image: mysql:5.6
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
      
    environment:
      - MYSQL_ROOT_PASSWORD=newPassword
      - MYSQL_DATABASE=app_development
  app:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    links:
      - db
    ports:
      - 80:80
    environment:
      - PMA_ARBITRARY=1
